# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 05b092f18b67ea458d80a3c0552351b90419349b97ed2ecfe2ff489f6a118fd88a60a80d375071996d492650327869fffa2a5aa62ca0d7226992f0293d97f7b1

test:
  secret_key_base: 19f83c76f768318c0ac64a64e8ec0fcccc79158797dca8b5afd0bcdb20cd2414ad2514d3be0379d686e1fba3d4f642aecb151388bde2e1ea01b693d03d2726ef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
